CREATE TABLE dbo.Buyer
(
	ID			INT IDENTITY (1,1) NOT NULL,
	Name		NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_dbo.Buyer] PRIMARY KEY CLUSTERED (Name)
);

CREATE TABLE dbo.Seller
(
	ID			INT IDENTITY (1,1) NOT NULL,
	Name		NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_dbo.Seller] PRIMARY KEY CLUSTERED (Name)
);

CREATE TABLE dbo.Item
(
	ID			INT IDENTITY (1,1) NOT NULL,
	Name		NVARCHAR(50) NOT NULL,
	Description NVARCHAR(300) NOT NULL,
	Seller		NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_dbo.Item] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_dbo.Seller] FOREIGN KEY (Seller)
		REFERENCES dbo.Seller (Name)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE dbo.Bid
(
	ID			INT IDENTITY (1,1) NOT NULL,
	ItemID		INT NOT NULL,
	Buyer		NVARCHAR(50) NOT NULL,
	Price		FLOAT NOT NULL,
	TimeStamp	DATETIME NOT NULL
	CONSTRAINT [PK_dbo.Bid] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_dbo.Bid] FOREIGN KEY (ItemID)
		REFERENCES dbo.Item (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
